// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqL4k2kou9f8v7YCClit-LUXkWMOIs1A',
    appId: '1:614179652274:web:b270cb38a668a05f08ffab',
    messagingSenderId: '614179652274',
    projectId: 'tutor-aid-14664',
    authDomain: 'tutor-aid-14664.firebaseapp.com',
    storageBucket: 'tutor-aid-14664.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-rBY2Lj3mDq0Spa-r0gcNE6sP3ZLTts',
    appId: '1:614179652274:android:40167f2e6ff4a97b08ffab',
    messagingSenderId: '614179652274',
    projectId: 'tutor-aid-14664',
    storageBucket: 'tutor-aid-14664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrio4zzT5-DGZ98_Y9rFORjwO9uT7FFg',
    appId: '1:614179652274:ios:50bb4e185873180f08ffab',
    messagingSenderId: '614179652274',
    projectId: 'tutor-aid-14664',
    storageBucket: 'tutor-aid-14664.appspot.com',
    iosBundleId: 'com.djeneba.tutoraid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGrio4zzT5-DGZ98_Y9rFORjwO9uT7FFg',
    appId: '1:614179652274:ios:084ecd764e8d298008ffab',
    messagingSenderId: '614179652274',
    projectId: 'tutor-aid-14664',
    storageBucket: 'tutor-aid-14664.appspot.com',
    iosBundleId: 'com.example.tutorAid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcqL4k2kou9f8v7YCClit-LUXkWMOIs1A',
    appId: '1:614179652274:web:c13ab78a0a6ce56908ffab',
    messagingSenderId: '614179652274',
    projectId: 'tutor-aid-14664',
    authDomain: 'tutor-aid-14664.firebaseapp.com',
    storageBucket: 'tutor-aid-14664.appspot.com',
  );
}